// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Note_Server.Data;

#nullable disable

namespace Note_Server.Migrations
{
    [DbContext(typeof(NotesDbContext))]
    [Migration("20251115113330_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Note_Server.Models.Note", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            Id = "a2a9d8c3-4e6f-4c5b-9d0a-1b3c4f5e6d7a",
                            Content = "Initial meeting notes for the new Q4 feature.",
                            CreatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Tag = "idea",
                            Title = "Project Alpha",
                            UpdatedAt = new DateTime(2025, 1, 1, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "b9b8c7a6-1d2e-3f4g-5h6i-7j8k9l0m1n2o",
                            Content = "My secret plan to take over the world. Only access with PIN.",
                            CreatedAt = new DateTime(2025, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc),
                            Tag = "confidential",
                            Title = "Hush Hush Details",
                            UpdatedAt = new DateTime(2025, 1, 1, 11, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = "c1c2d3e4-5f6g-7h8i-9j0k-1l2m3n4o5p6q",
                            Content = "Milk, Eggs, Bread.",
                            CreatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Tag = "todo",
                            Title = "Grocery List",
                            UpdatedAt = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
